/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_syeyoung_fluttermc_FlutterGuiScreen */

#ifndef _Included_com_syeyoung_fluttermc_FlutterGuiScreen
#define _Included_com_syeyoung_fluttermc_FlutterGuiScreen
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_syeyoung_fluttermc_FlutterGuiScreen
 * Method:    startFlutter
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_syeyoung_fluttermc_FlutterGuiScreen_startFlutter
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_syeyoung_fluttermc_FlutterGuiScreen
 * Method:    bindTexture
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_syeyoung_fluttermc_FlutterGuiScreen_bindTexture
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_syeyoung_fluttermc_FlutterGuiScreen
 * Method:    resize
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_syeyoung_fluttermc_FlutterGuiScreen_resize
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     com_syeyoung_fluttermc_FlutterGuiScreen
 * Method:    mouseEvent
 * Signature: (JIIII)V
 */
JNIEXPORT void JNICALL Java_com_syeyoung_fluttermc_FlutterGuiScreen_mouseEvent
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint);

/*
 * Class:     com_syeyoung_fluttermc_FlutterGuiScreen
 * Method:    scrollEvent
 * Signature: (JIII)V
 */
JNIEXPORT void JNICALL Java_com_syeyoung_fluttermc_FlutterGuiScreen_scrollEvent
  (JNIEnv *, jclass, jlong, jint, jint, jint);

/*
 * Class:     com_syeyoung_fluttermc_FlutterGuiScreen
 * Method:    keyEvent
 * Signature: (JIIIC)Z
 */
JNIEXPORT jboolean JNICALL Java_com_syeyoung_fluttermc_FlutterGuiScreen_keyEvent
  (JNIEnv *, jclass, jlong, jint, jint, jint, jchar);

/*
 * Class:     com_syeyoung_fluttermc_FlutterGuiScreen
 * Method:    runTasks
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_syeyoung_fluttermc_FlutterGuiScreen_runTasks
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
